# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The python orb contains a set of prepackaged circleci configuration you can use repeatedly in your configurations files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  linter:
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: flake8
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: python setup.py install
      - run:
          command: pytest
  deploy-pypi-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: build pkg
          command: |
            python -m pip install --upgrade build
            python -m build
      - run:
          name: upload to test pypi
          command: |
            python -m pip install --upgrade twine
            python -m twine upload --repository testpypi --non-interactive --skip-existing -u __token__ -p $TWINE_TEST_TOKEN dist/*
  deploy-pypi:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:  
          name: build pkg
          command: |
            python -m pip install --upgrade build
            python -m build
      - run:
          name: build and upload to pypi
          command: |
            python -m pip install --upgrade twine
            python -m twine upload --non-interactive -u __token__ -p $TWINE_TOKEN dist/*

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-deploy:
    jobs:
      - linter:
          filters:
            tags:
              only: /.*/
      - build-and-test:
          requires:
            - linter
          filters:
            tags:
              only: /.*/
      - deploy-pypi-test:
          requires:
            - build-and-test
          filters:
            tags:
              only: v(\d+)\.(\d+).(\d+)-rc(\d+)
            branches:
              ignore: /.*/
      - deploy-pypi:
          requires:
            - build-and-test
          filters:
            tags:
              only: v(\d+)\.(\d+).(\d+)
            branches:
              ignore: /.*/
